version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    volumes:
      - ./data/:/data/db
    restart: always

  bitcore-node:
    build: .
    image: bitcore-node
    links:
      - database
    depends_on:
      - database
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database
    env_file: .env
    restart: always
    command: npm run node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/XVG/mainnet/block/tip"]
      interval: 1m
      timeout: 10s
      retries: 2

  bitcore-wallet-service:
    build: .
    image: bitcore-wallet-service
    links:
      - database
      - bitcore-node
    depends_on:
      - database
    ports:
      - 3232:3232
      - 3380:3380
    environment:
      - BWS_MONGODB_URI=mongodb://database:27017/bws
      - BWS_NODE_URL=http://host.docker.internal:3000
    env_file: .env
    restart: always
    command: ./packages/bitcore-wallet-service/docker-cmd.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3232/vws/api/v1/fiatrates/eur"]
      interval: 1m
      timeout: 10s
      retries: 1

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
