version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    volumes:
      - ./data/:/data/db

  bitcore-node:
    build: .
    image: bitcore-node
    links:
      - database
    ports:
      - 3000:3000
      - 3232:3232
      - 3380:3380
    environment:
      - DB_HOST=database
      - BWS_MONGODB_URI=mongodb://host.docker.internal:27017/bws
    env_file: .env
